
name: Mohnish Jadwani
title: Mohnish Jadwani
description: "Mohnish's experiences, reflections and learnings related to programming and people"
url: https://www.mohnishjadwani.com/
highlighter: rouge
permalink: /posts/:title/
markdown: kramdown

theme_options:
  disqus_shortname: mohnishj
  google_analytics: UA-67882335-1
  twitter_handle: mohnishgj

sass:
  sass_dir: _sass
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
